apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: postgres
spec:
  containers:
    - name: db
      image: postgres
      ports:
      - containerPort: 5432
      env:
        - name: POSTRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust