apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
      app: demo-voting-app
  template:
    metadata:
      name: db
      labels:
        name: db
        app: demo-voting-app
    spec:
      containers:
      - name: db
        image: postgres
        ports:
          - containerPort: 5432
        env:
          - name: POSTRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
    